import { Locale } from "@/types/locale";

export const SITE_CONFIG = {
  name: "West Java Diving",
  shortName: "WJ Diving",
  defaultLocale: "en" as Locale,
  locales: ["en", "id"] as const,
  taglines: {
    en: "Premier Underwater Expeditions & Diving in West Java, Indonesia",
    id: "Petualangan Bawah Laut & Ekspedisi Selam Terkemuka di Jawa Barat",
  },
  descriptions: {
    en: "Professional underwater adventure operator in West Java, Indonesia. Curated expeditions, training, and trips for Spearfishing, Freediving, and Scuba Diving with uncompromising safety standards.",
    id: "Operator petualangan bawah laut profesional di Jawa Barat, Indonesia. Menghadirkan trip & edukasi terstruktur untuk Spearfishing, Freediving, dan Scuba Diving dengan prioritas keselamatan utama.",
  },
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://westjavaspearfishing.com",
  ogImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "6281234567890",
  whatsappDisplay: "+62 812-3456-7890",
  email: "contact@westjavaspearfishing.com",
  location: {
    en: "West Java, Indonesia",
    id: "Jawa Barat, Indonesia",
  },
  socials: {
    instagram: "https://instagram.com/westjavadiving",
    youtube: "https://youtube.com/@westjavadiving",
    tiktok: "https://tiktok.com/@westjavadiving",
  },
};

export const UI_DICTIONARY = {
  en: {
    nav: {
      experiences: "Experiences",
      trips: "Trips & Packages",
      diveSites: "Dive Sites",
      gallery: "Gallery",
      about: "About",
      faq: "FAQ",
      contact: "Contact",
      bookTrip: "Book Your Trip",
      exploreTrips: "Explore Trips",
      allTrips: "All Trips & Packages",
      spearfishingTrips: "Spearfishing Trips",
      freedivingTrips: "Freediving Trips",
      scubaTrips: "Scuba Diving Trips",
      privateTrips: "Private & Custom Charters",
    },
    common: {
      startingFrom: "Starting from",
      viewDetails: "View Trip Details",
      bookWhatsApp: "Book via WhatsApp",
      sendInquiry: "Send Booking Inquiry",
      duration: "Duration",
      location: "Location",
      meetingPoint: "Meeting Point (MEPO)",
      startPoint: "Departure Harbour / Start Point",
      groupSize: "Group Size",
      level: "Skill Level",
      format: "Trip Format",
      activity: "Activity",
      highlights: "Highlights",
      itinerary: "Itinerary",
      inclusions: "What's Included",
      exclusions: "What's Not Included",
      requirements: "Prerequisites & Requirements",
      safetyNotes: "Ocean Safety Protocols",
      conditions: "Ocean Conditions",
      divePoints: "Dive Points",
      marineLife: "Marine Life",
      access: "Access & Boat Transport",
      relatedTrips: "Related Trips & Packages",
      relatedDiveSites: "Recommended Dive Sites",
      home: "Home",
      resetFilters: "Reset All Filters",
      showing: "Showing",
      availableTrips: "available trips",
      noResults: "No trips found matching the selected filters.",
      viewAllTrips: "View All Trips",
      allActivities: "All Activities",
      allFormats: "All Formats",
      allLevels: "All Levels",
      customTripCTA: "Customize Your Expedition",
    },
    footer: {
      safetyNotice: "Uncompromising Safety & Ethical Ocean Exploration",
      safetySub: "Standardized dive profiles, certified guides, emergency O2 units, and local marine conservation.",
      quickWhatsApp: "Chat with Us on WhatsApp",
      quickLinks: "Quick Navigation",
      rightsReserved: "All rights reserved. Operating in West Java, Indonesia.",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
    },
    bookingModal: {
      title: "Send a Booking Inquiry",
      subtitle: "Fill in your details below and our team will get back to you with confirmed availability and logistics.",
      fullName: "Full Name",
      nationality: "Nationality / Country of Origin",
      email: "Email Address",
      phone: "WhatsApp / Phone Number",
      selectedTrip: "Selected Trip / Package",
      preferredDate: "Preferred Trip Date",
      guestCount: "Number of Guests",
      tripType: "Preferred Format",
      experienceLevel: "Your Experience Level",
      message: "Additional Questions / Special Requests",
      submitBtn: "Submit Booking Inquiry",
      submitting: "Submitting...",
      successTitle: "Inquiry Sent Successfully!",
      successDesc: "Thank you for reaching out. Our expedition coordinator will review your request and contact you via Email and WhatsApp within 24 hours.",
      close: "Close",
    },
  },
  id: {
    nav: {
      experiences: "Experiences",
      trips: "Trips & Paket",
      diveSites: "Dive Sites",
      gallery: "Galeri",
      about: "Tentang Kami",
      faq: "FAQ",
      contact: "Kontak",
      bookTrip: "Pesan Trip",
      exploreTrips: "Jelajahi Trip",
      allTrips: "Semua Trip & Paket",
      spearfishingTrips: "Trip Spearfishing",
      freedivingTrips: "Trip Freediving",
      scubaTrips: "Trip Scuba Diving",
      privateTrips: "Trip Privat & Custom",
    },
    common: {
      startingFrom: "Mulai dari",
      viewDetails: "Lihat Detail Trip",
      bookWhatsApp: "Book via WhatsApp",
      sendInquiry: "Kirim Formulir Inquiry",
      duration: "Durasi",
      location: "Lokasi",
      meetingPoint: "Titik Kumpul (MEPO)",
      startPoint: "Dermaga Keberangkatan",
      groupSize: "Kapasitas Grup",
      level: "Level Kualifikasi",
      format: "Format Trip",
      activity: "Aktivitas",
      highlights: "Sorotan Utama",
      itinerary: "Itinerary Perjalanan",
      inclusions: "Fasilitas Termasuk",
      exclusions: "Belum Termasuk",
      requirements: "Prasyarat & Kebutuhan",
      safetyNotes: "Protokol Keselamatan Laut",
      conditions: "Kondisi Perairan",
      divePoints: "Titik Selam",
      marineLife: "Biota Laut",
      access: "Akses & Transportasi Kapal",
      relatedTrips: "Trip & Paket Terkait",
      relatedDiveSites: "Dive Sites Rekomendasi",
      home: "Beranda",
      resetFilters: "Reset Semua Filter",
      showing: "Menampilkan",
      availableTrips: "trip tersedia",
      noResults: "Tidak ditemukan paket trip dengan kombinasi filter yang dipilih.",
      viewAllTrips: "Lihat Semua Paket",
      allActivities: "Semua Aktivitas",
      allFormats: "Semua Format",
      allLevels: "Semua Level",
      customTripCTA: "Rancang Ekspedisi Kustom",
    },
    footer: {
      safetyNotice: "Prioritas Keselamatan & Konservasi Laut",
      safetySub: "Penyelaman terstandarisasi, pengawasan instruktur bersertifikat, unit O2 darurat, dan etika laut.",
      quickWhatsApp: "Konsultasi via WhatsApp",
      quickLinks: "Navigasi Cepat",
      rightsReserved: "Hak cipta dilindungi. Beroperasi di Jawa Barat, Indonesia.",
      privacy: "Kebijakan Privasi",
      terms: "Syarat & Ketentuan",
    },
    bookingModal: {
      title: "Ajukan Permintaan Booking",
      subtitle: "Lengkapi data di bawah ini dan tim kami akan segera menghubungi Anda untuk konfirmasi jadwal dan logistik.",
      fullName: "Nama Lengkap",
      nationality: "Kewarganegaraan / Asal",
      email: "Alamat Email",
      phone: "Nomor WhatsApp / HP",
      selectedTrip: "Paket Trip Pilihan",
      preferredDate: "Estimasi Tanggal Trip",
      guestCount: "Jumlah Peserta",
      tripType: "Pilihan Format Trip",
      experienceLevel: "Tingkat Pengalaman Selam",
      message: "Catatan Tambahan / Permintaan Khusus",
      submitBtn: "Kirim Permintaan Booking",
      submitting: "Mengirimkan...",
      successTitle: "Permintaan Booking Terkirim!",
      successDesc: "Terima kasih. Koordinator ekspedisi kami akan meninjau permintaan Anda dan menghubungi via Email / WhatsApp dalam 24 jam.",
      close: "Tutup",
    },
  },
};
